CREATE TABLE "Nation" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"name" VARCHAR(100) NOT NULL,
	"code" VARCHAR(3),
	PRIMARY KEY("id")
);

CREATE TABLE "Stadium" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"name" VARCHAR(255) NOT NULL,
	"city" VARCHAR(100),
	"nation_id" INTEGER REFERENCES "Nation"("id"),
	"capacity" INTEGER,
	"opened_year" INTEGER,
	"surface_type" VARCHAR(50),
	"length_m" DECIMAL(6,2),
	"width_m" DECIMAL(6,2),
	"coordinate_system" VARCHAR(50),
	"origin_description" TEXT,
	"altitude_m" INTEGER,
	"has_roof" BOOLEAN DEFAULT false,
	"created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	"updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	"created_by" VARCHAR(100),
	PRIMARY KEY("id")
);

CREATE TABLE "Competition" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"name" VARCHAR(255) NOT NULL,
	"season" VARCHAR(20),
	"competition_type" VARCHAR(50),
	"nation_id" INTEGER REFERENCES "Nation"("id"),
	PRIMARY KEY("id")
);

CREATE TABLE "Leg" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	PRIMARY KEY("id")
);

CREATE TABLE "Match" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"competition_id" INTEGER NOT NULL REFERENCES "Competition"("id"),
	"stadium_id" INTEGER NOT NULL REFERENCES "Stadium"("id"),
	"leg_id" INTEGER NOT NULL REFERENCES "Leg"("id"),
	"match_date" DATE NOT NULL,
	"match_time" TIME,
	"matchday" INTEGER,
	"status" VARCHAR(20),
	"attendance" INTEGER,
	"weather" VARCHAR(50),
	"temperature_celsius" INTEGER,
	"created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	"updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	"created_by" VARCHAR(100),
	PRIMARY KEY("id")
);

CREATE TABLE "Team" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"name" VARCHAR(255) NOT NULL,
	"short_name" VARCHAR(50),
	"founded_year" INTEGER,
	"city" VARCHAR(100),
	"home_stadium_id" INTEGER REFERENCES "Stadium"("id"),
	PRIMARY KEY("id")
);

CREATE TABLE "Team_Game" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"team_id" INTEGER NOT NULL REFERENCES "Team"("id"),
	"match_id" INTEGER NOT NULL REFERENCES "Match"("id"),
	"is_home" BOOLEAN,
	"final_score" INTEGER,
	"formation" VARCHAR(20),
	"possession_percentage" DECIMAL(5,2),
	"shots" INTEGER,
	"shots_on_target" INTEGER,
	"corners" INTEGER,
	"fouls" INTEGER,
	"yellow_cards" INTEGER,
	"red_cards" INTEGER,
	"created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	"updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	"created_by" VARCHAR(100),
	PRIMARY KEY("id"),
	CONSTRAINT "unique_team_match" UNIQUE("team_id", "match_id")
);

CREATE TABLE "Staff" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"name" VARCHAR(255) NOT NULL,
	"date_of_birth" DATE,
	"nation_id" INTEGER REFERENCES "Nation"("id"),
	"role" VARCHAR(100),
	"license_level" VARCHAR(50),
	PRIMARY KEY("id")
);

CREATE TABLE "Player" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"team_id" INTEGER REFERENCES "Team"("id"),
	"name" VARCHAR(255) NOT NULL,
	"date_of_birth" DATE,
	"nation_id" INTEGER REFERENCES "Nation"("id"),
	"position" VARCHAR(50),
	"jersey_number" INTEGER,
	"height_cm" INTEGER,
	"weight_kg" INTEGER,
	"preferred_foot" VARCHAR(10),
	"contract_start" DATE,
	"contract_end" DATE,
	"market_value_euros" BIGINT,
	"is_active" BOOLEAN DEFAULT true,
	"created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	"updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	"created_by" VARCHAR(100),
	PRIMARY KEY("id")
);

CREATE TABLE "Role" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"player_id" INTEGER NOT NULL REFERENCES "Player"("id"),
	"team_game_id" INTEGER NOT NULL REFERENCES "Team_Game"("id"),
	"is_starter" BOOLEAN,
	"is_captain" BOOLEAN,
	"is_vice_captain" BOOLEAN,
	"minutes_played" INTEGER,
	"position_played" VARCHAR(50),
	"jersey_number" INTEGER,
	"created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	"updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	"created_by" VARCHAR(100),
	PRIMARY KEY("id"),
	CONSTRAINT "unique_player_team_game" UNIQUE("player_id", "team_game_id")
);

CREATE TABLE "Tracking" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"player_id" INTEGER NOT NULL REFERENCES "Player"("id"),
	"team_game_id" INTEGER NOT NULL REFERENCES "Team_Game"("id"),
	"total_distance_m" DECIMAL(8,2),
	"max_speed_kmh" DECIMAL(5,2),
	"average_speed_kmh" DECIMAL(5,2),
	"high_intensity_distance_m" DECIMAL(8,2),
	"sprints_count" INTEGER,
	"accelerations_count" INTEGER,
	"decelerations_count" INTEGER,
	"heart_rate_avg" INTEGER,
	"heart_rate_max" INTEGER,
	PRIMARY KEY("id")
);

CREATE TABLE "Ball_Tracking" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"match_id" INTEGER NOT NULL REFERENCES "Match"("id"),
	"timestamp" TIMESTAMP,
	"x_coordinate" DECIMAL(6,2),
	"y_coordinate" DECIMAL(6,2),
	"z_coordinate" DECIMAL(6,2),
	"velocity_x" DECIMAL(6,2),
	"velocity_y" DECIMAL(6,2),
	"velocity_z" DECIMAL(6,2),
	"ball_speed_kmh" DECIMAL(6,2),
	PRIMARY KEY("id")
);

CREATE TABLE "Referee" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"name" VARCHAR(255) NOT NULL,
	"date_of_birth" DATE,
	"nation_id" INTEGER REFERENCES "Nation"("id"),
	"license_level" VARCHAR(50),
	PRIMARY KEY("id")
);

CREATE TABLE "Referee_Game" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"referee_id" INTEGER NOT NULL REFERENCES "Referee"("id"),
	"match_id" INTEGER NOT NULL REFERENCES "Match"("id"),
	"referee_type" VARCHAR(50),
	PRIMARY KEY("id")
);

CREATE TABLE "Action_Document" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"team_game_id" INTEGER NOT NULL REFERENCES "Team_Game"("id"),
	"file_path" TEXT,
	"document_type" VARCHAR(50),
	"created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY("id")
);

CREATE TABLE "Action_Video" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"team_game_id" INTEGER NOT NULL REFERENCES "Team_Game"("id"),
	"file_path" TEXT,
	"video_type" VARCHAR(50),
	"duration_seconds" INTEGER,
	"created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY("id")
);

CREATE TABLE "Pass" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"player_id" INTEGER NOT NULL REFERENCES "Player"("id"),
	"action_document_id" INTEGER REFERENCES "Action_Document"("id"),
	"action_video_id" INTEGER REFERENCES "Action_Video"("id"),
	"match_minute" INTEGER,
	"timestamp_seconds" INTEGER,
	"pass_type" VARCHAR(50),
	"start_x" DECIMAL(6,2),
	"start_y" DECIMAL(6,2),
	"end_x" DECIMAL(6,2),
	"end_y" DECIMAL(6,2),
	"distance_m" DECIMAL(6,2),
	"outcome" VARCHAR(20),
	"receiver_player_id" INTEGER REFERENCES "Player"("id"),
	PRIMARY KEY("id")
);

CREATE TABLE "Duel" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"player_id" INTEGER NOT NULL REFERENCES "Player"("id"),
	"action_document_id" INTEGER REFERENCES "Action_Document"("id"),
	"action_video_id" INTEGER REFERENCES "Action_Video"("id"),
	"match_minute" INTEGER,
	"timestamp_seconds" INTEGER,
	"duel_type" VARCHAR(50),
	"outcome" VARCHAR(20),
	"opponent_player_id" INTEGER REFERENCES "Player"("id"),
	"x_coordinate" DECIMAL(6,2),
	"y_coordinate" DECIMAL(6,2),
	PRIMARY KEY("id")
);

CREATE TABLE "Assist" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"player_id" INTEGER NOT NULL REFERENCES "Player"("id"),
	"action_document_id" INTEGER REFERENCES "Action_Document"("id"),
	"action_video_id" INTEGER REFERENCES "Action_Video"("id"),
	"match_minute" INTEGER,
	"timestamp_seconds" INTEGER,
	"assist_type" VARCHAR(50),
	"goal_scorer_id" INTEGER REFERENCES "Player"("id"),
    "goal_id" INTEGER REFERENCES "Goal"("id"),
	"x_coordinate" DECIMAL(6,2),
	"y_coordinate" DECIMAL(6,2),
	PRIMARY KEY("id")
);

CREATE TABLE "Goal" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"player_id" INTEGER NOT NULL REFERENCES "Player"("id"),
	"action_document_id" INTEGER REFERENCES "Action_Document"("id"),
	"action_video_id" INTEGER REFERENCES "Action_Video"("id"),
	"match_minute" INTEGER,
	"timestamp_seconds" INTEGER,
	"goal_type" VARCHAR(50),
	"body_part" VARCHAR(20),
	"x_coordinate" DECIMAL(6,2),
	"y_coordinate" DECIMAL(6,2),
	"assisting_player_id" INTEGER REFERENCES "Player"("id"),
	PRIMARY KEY("id")
);

CREATE TABLE "Card" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"player_id" INTEGER NOT NULL REFERENCES "Player"("id"),
	"card_type" VARCHAR(20),
	"match_minute" INTEGER,
	"timestamp_seconds" INTEGER,
	"reason" VARCHAR(255),
	"action_document_id" INTEGER REFERENCES "Action_Document"("id"),
	"action_video_id" INTEGER REFERENCES "Action_Video"("id"),
	PRIMARY KEY("id")
);

CREATE TABLE "Freekick" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"player_id" INTEGER NOT NULL REFERENCES "Player"("id"),
	"action_document_id" INTEGER REFERENCES "Action_Document"("id"),
	"action_video_id" INTEGER REFERENCES "Action_Video"("id"),
	"match_minute" INTEGER,
	"timestamp_seconds" INTEGER,
	"freekick_type" VARCHAR(20),
	"outcome" VARCHAR(30),
	"x_coordinate" DECIMAL(6,2),
	"y_coordinate" DECIMAL(6,2),
	PRIMARY KEY("id")
);

CREATE TABLE "Training" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"team_id" INTEGER NOT NULL REFERENCES "Team"("id"),
	"training_date" DATE NOT NULL,
	"training_type" VARCHAR(50),
	"duration_minutes" INTEGER,
	"location" VARCHAR(255),
	PRIMARY KEY("id")
);

CREATE TABLE "Training_Exercise" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"training_id" INTEGER NOT NULL REFERENCES "Training"("id"),
	"exercise_name" VARCHAR(255) NOT NULL,
	"exercise_type" VARCHAR(50),
	"duration_minutes" INTEGER,
	"intensity" VARCHAR(20),
	"description" TEXT,
	PRIMARY KEY("id")
);

CREATE TABLE "Wellness_Test" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"player_id" INTEGER NOT NULL REFERENCES "Player"("id"),
	"test_date" DATE NOT NULL,
	"fatigue_score" INTEGER,
	"stress_score" INTEGER,
	"sleep_quality_score" INTEGER,
	"muscle_soreness_score" INTEGER,
	"mood_score" INTEGER,
	"readiness_score" INTEGER,
	"comments" TEXT,
	PRIMARY KEY("id")
);

CREATE TABLE "Satisfaction_Test" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"player_id" INTEGER NOT NULL REFERENCES "Player"("id"),
	"test_date" DATE NOT NULL,
	"coach_relationship_score" INTEGER,
	"team_atmosphere_score" INTEGER,
	"playing_time_satisfaction" INTEGER,
	"training_quality_score" INTEGER,
	"overall_satisfaction" INTEGER,
	"comments" TEXT,
	PRIMARY KEY("id")
);

CREATE TABLE "Physical_Test" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"player_id" INTEGER NOT NULL REFERENCES "Player"("id"),
	"test_date" DATE NOT NULL,
	"test_type" VARCHAR(50),
	"result_value" DECIMAL(8,2),
	"result_unit" VARCHAR(20),
	"baseline_value" DECIMAL(8,2),
	"test_conditions" TEXT,
	PRIMARY KEY("id")
);

CREATE TABLE "Injury" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"player_id" INTEGER NOT NULL REFERENCES "Player"("id"),
	"injury_date" DATE NOT NULL,
	"injury_type" VARCHAR(100),
	"severity" VARCHAR(20),
	"expected_recovery_days" INTEGER,
	"actual_recovery_days" INTEGER,
	"injury_context" VARCHAR(255),
	"return_date" DATE,
	"treatment_notes" TEXT,
	PRIMARY KEY("id")
);

CREATE TABLE "Bodypart" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"injury_id" INTEGER NOT NULL REFERENCES "Injury"("id"),
	"body_part" VARCHAR(50),
	"laterality" VARCHAR(10),
	"specific_location" VARCHAR(100),
	PRIMARY KEY("id")
);

CREATE TABLE "Staff_Team" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"staff_id" INTEGER NOT NULL REFERENCES "Staff"("id"),
	"team_id" INTEGER NOT NULL REFERENCES "Team"("id"),
	"start_date" DATE,
	"end_date" DATE,
	"is_active" BOOLEAN DEFAULT true,
	PRIMARY KEY("id")
);

CREATE TABLE "Staff_Game" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"staff_id" INTEGER NOT NULL REFERENCES "Staff"("id"),
	"team_game_id" INTEGER NOT NULL REFERENCES "Team_Game"("id"),
	"role_in_game" VARCHAR(100),
	PRIMARY KEY("id")
);

CREATE TABLE "Action_Document_Staff" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"staff_id" INTEGER NOT NULL REFERENCES "Staff"("id"),
	"team_game_id" INTEGER NOT NULL REFERENCES "Team_Game"("id"),
	"document_type" VARCHAR(50),
	"file_path" TEXT,
	"created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY("id")
);

CREATE TABLE "Substitution" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"match_id" INTEGER NOT NULL REFERENCES "Match"("id"),
	"team_game_id" INTEGER NOT NULL REFERENCES "Team_Game"("id"),
	"player_out_id" INTEGER NOT NULL REFERENCES "Player"("id"),
	"player_in_id" INTEGER NOT NULL REFERENCES "Player"("id"),
	"minute" INTEGER NOT NULL,
	"reason" VARCHAR(50),
	"created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	"updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	"created_by" VARCHAR(100),
	PRIMARY KEY("id")
);


-- ESSENTIAL INDEXES FOR PERFORMANCE
CREATE INDEX "idx_match_date" ON "Match"("match_date");
CREATE INDEX "idx_match_stadium" ON "Match"("stadium_id");
CREATE INDEX "idx_match_leg" ON "Match"("leg_id");
CREATE INDEX "idx_match_competition" ON "Match"("competition_id");
CREATE INDEX "idx_team_home_stadium" ON "Team"("home_stadium_id");
CREATE INDEX "idx_player_team" ON "Player"("team_id");
CREATE INDEX "idx_player_nation" ON "Player"("nation_id");
CREATE INDEX "idx_team_game_match" ON "Team_Game"("match_id");
CREATE INDEX "idx_team_game_team" ON "Team_Game"("team_id");
CREATE INDEX "idx_role_player" ON "Role"("player_id");
CREATE INDEX "idx_role_team_game" ON "Role"("team_game_id");
CREATE INDEX "idx_tracking_player" ON "Tracking"("player_id");
CREATE INDEX "idx_tracking_team_game" ON "Tracking"("team_game_id");

-- Action table indexes
CREATE INDEX "idx_pass_player" ON "Pass"("player_id");
CREATE INDEX "idx_pass_minute" ON "Pass"("match_minute");
CREATE INDEX "idx_goal_player" ON "Goal"("player_id");
CREATE INDEX "idx_goal_minute" ON "Goal"("match_minute");
CREATE INDEX "idx_assist_player" ON "Assist"("player_id");
CREATE INDEX "idx_duel_player" ON "Duel"("player_id");
CREATE INDEX "idx_card_player" ON "Card"("player_id");
CREATE INDEX "idx_freekick_player" ON "Freekick"("player_id");

-- Staff and referee indexes
CREATE INDEX "idx_staff_nation" ON "Staff"("nation_id");
CREATE INDEX "idx_referee_nation" ON "Referee"("nation_id");
CREATE INDEX "idx_staff_team_staff" ON "Staff_Team"("staff_id");
CREATE INDEX "idx_staff_team_team" ON "Staff_Team"("team_id");
CREATE INDEX "idx_referee_game_match" ON "Referee_Game"("match_id");

-- Training and test indexes
CREATE INDEX "idx_training_team" ON "Training"("team_id");
CREATE INDEX "idx_training_date" ON "Training"("training_date");
CREATE INDEX "idx_wellness_test_player" ON "Wellness_Test"("player_id");
CREATE INDEX "idx_wellness_test_date" ON "Wellness_Test"("test_date");
CREATE INDEX "idx_satisfaction_test_player" ON "Satisfaction_Test"("player_id");
CREATE INDEX "idx_physical_test_player" ON "Physical_Test"("player_id");
CREATE INDEX "idx_injury_player" ON "Injury"("player_id");
CREATE INDEX "idx_injury_date" ON "Injury"("injury_date");
CREATE INDEX "idx_substitution_match" ON "Substitution"("match_id");
CREATE INDEX "idx_substitution_team_game" ON "Substitution"("team_game_id");